import groovy.json.JsonSlurper

plugins {
    java
    application
    id("org.graalvm.buildtools.native") version "1.1.14"
}

group = "dev.ping"

// The desktop package.json owns the app version. A release build overrides it with
// -PappVersion so the native core matches the tag before the shell has been versioned.
val appVersion: String = (project.findProperty("appVersion") as String?)
    ?: (JsonSlurper().parse(file("../desktop/package.json")) as Map<*, *>)["version"].toString()

version = appVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.22.2")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.22.2")

    testImplementation(platform("org.junit:junit-bom:6.1.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
    mainClass = "dev.ping.Main"
    applicationName = "ping-core"
}

tasks.test {
    useJUnitPlatform()
}

if (project.hasProperty("agent")) {
    tasks.test {
        javaLauncher = javaToolchains.launcherFor {
            languageVersion = JavaLanguageVersion.of(25)
            vendor = JvmVendorSpec.GRAAL_VM
        }
    }
}

graalvmNative {
    metadataRepository {
        enabled = true
    }

    binaries {
        named("main") {
            imageName = "ping-core"
            mainClass = "dev.ping.Main"

            buildArgs.add("--no-fallback")
            buildArgs.add("-O2")

            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(25)
                vendor = JvmVendorSpec.GRAAL_VM
            }
        }
    }
}

// BuildInfo is generated rather than hand-maintained so the core cannot report a version the
// shell disagrees with. A compiled constant keeps native-image from needing a resource-config
// entry, unlike a classpath properties file.
val generatedBuildInfoDir = layout.buildDirectory.dir("generated/sources/build-info/java")

val generateBuildInfo by tasks.registering {
    val version = appVersion
    val outputDir = generatedBuildInfoDir
    inputs.property("version", version)
    outputs.dir(outputDir)

    doLast {
        val source = outputDir.get().file("dev/ping/BuildInfo.java").asFile
        source.parentFile.mkdirs()
        source.writeText(
            """
            package dev.ping;

            /** Generated by the generateBuildInfo task. Do not edit. */
            public final class BuildInfo {
                public static final String VERSION = "$version";

                private BuildInfo() {
                }
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets {
    main {
        java.srcDir(generateBuildInfo)
    }
}

tasks.compileJava {
    dependsOn(generateBuildInfo)
}
