import groovy.json.JsonSlurper

plugins {
    java
    application
    id("org.graalvm.buildtools.native") version "1.1.14"
}

group = "dev.ping"

// The desktop package.json owns the app version. A release build overrides it with
// -PappVersion so the native core matches the tag before the shell has been versioned.
val appVersion: String = (project.findProperty("appVersion") as String?)
    ?: (JsonSlurper().parse(file("../desktop/package.json")) as Map<*, *>)["version"].toString()

version = appVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.22.3")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.22.3")

    testImplementation(platform("org.junit:junit-bom:6.1.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
    mainClass = "dev.ping.Main"
    applicationName = "ping-core"
}

tasks.test {
    useJUnitPlatform()
    // The JDK reads this once, when its first HttpClient loads, and any earlier test may have made
    // one; the core sets the same value itself at startup (see HttpEngine).
    systemProperty("jdk.http.auth.tunneling.disabledSchemes", "")
    // A file name crosses to the OS as sun.jnu.encoding, which JEP 400 left tied to the locale
    // rather than moving it to UTF-8 with file.encoding. The worker inherits that locale from
    // whichever environment started the Gradle daemon, so a suite that writes a non-ASCII file
    // name passes or fails by which daemon it lands on. C.UTF-8 needs no generated locale.
    environment("LC_ALL", "C.UTF-8")
}

if (project.hasProperty("agent")) {
    tasks.test {
        javaLauncher = javaToolchains.launcherFor {
            languageVersion = JavaLanguageVersion.of(25)
            vendor = JvmVendorSpec.GRAAL_VM
        }
    }
}

graalvmNative {
    metadataRepository {
        enabled = true
    }

    binaries {
        named("main") {
            imageName = "ping-core"
            mainClass = "dev.ping.Main"

            buildArgs.add("--no-fallback")
            buildArgs.add("-O2")

            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(25)
                vendor = JvmVendorSpec.GRAAL_VM
            }
        }
        named("test") {
            // The JDK reads jdk.http.auth.tunneling.disabledSchemes once, when its first HttpClient
            // loads. The core sets it at startup, before any client; a test binary has no startup, and
            // an earlier test may already have made a client, so it is given the same value as the core.
            runtimeArgs.add("-Djdk.http.auth.tunneling.disabledSchemes=")
        }
    }
}

// BuildInfo is generated rather than hand-maintained so the core cannot report a version the
// shell disagrees with. A compiled constant keeps native-image from needing a resource-config
// entry, unlike a classpath properties file.
val generatedBuildInfoDir = layout.buildDirectory.dir("generated/sources/build-info/java")

val generateBuildInfo = tasks.register("generateBuildInfo") {
    val version = appVersion
    val outputDir = generatedBuildInfoDir
    inputs.property("version", version)
    outputs.dir(outputDir)

    doLast {
        val source = outputDir.get().file("dev/ping/BuildInfo.java").asFile
        source.parentFile.mkdirs()
        source.writeText(
            """
            package dev.ping;

            /** Generated by the generateBuildInfo task. Do not edit. */
            public final class BuildInfo {
                public static final String VERSION = "$version";

                private BuildInfo() {
                }
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets {
    main {
        java.srcDir(generateBuildInfo)
    }
}

tasks.compileJava {
    dependsOn(generateBuildInfo)
}
